# Generated by Django 4.0 on 2023-02-04 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Admin', 'Admin'), ('Sysadmin', 'Sysadmin'), ('HR', 'HR')], default='Employee', max_length=250),
        ),
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 4, 14, 45, 41, 542686, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 4, 14, 45, 41, 543684, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
