# Generated by Django 4.0 on 2023-02-05 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customuser_role_alter_computers_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 5, 13, 57, 10, 117180, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='position',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='api.position', to_field='pos', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 5, 13, 57, 10, 117180, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
