# Generated by Django 4.0 on 2023-02-05 14:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_computers_arrival_date_alter_emp_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 5, 14, 2, 11, 899365, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 2, 5, 14, 2, 11, 900411, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
