# Generated by Django 4.0 on 2023-03-02 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_repairrequests_sys_id_alter_computers_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Employee', 'Employee'), ('SysAdmin', 'SysAdmin'), ('HR', 'HR')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 2, 12, 35, 54, 561046, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 3, 2, 12, 35, 54, 561046, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
