# Generated by Django 4.0 on 2023-04-15 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_surname_alter_computers_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 15, 10, 52, 20, 731546, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Админ'), ('Employee', 'Сотрудник'), ('SysAdmin', 'Сисадмин'), ('HR', 'HR')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='api.emp', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата регистрации'),
        ),
    ]
