# Generated by Django 4.0 on 2023-04-16 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_computers_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 4, 16, 17, 58, 19, 69345, tzinfo=utc), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_id', to='api.emp', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='sys_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sys_id', to='api.emp', unique=True, verbose_name='Сисадмин'),
        ),
    ]
