# Generated by Django 4.0 on 2023-04-25 04:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_computers_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 4, 25), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='computers',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.emp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Админ', 'Админ'), ('Сотрудник', 'Сотрудник'), ('Сисадмин', 'Сисадмин'), ('HR', 'HR')], default='Employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='sys_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sys_id', to='api.emp', verbose_name='Сисадмин'),
        ),
    ]
