# Generated by Django 4.0 on 2023-05-06 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_emp_email_emp_phone_emp_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 6), verbose_name='Дата прибытия'),
        ),
    ]
