# Generated by Django 4.0 on 2023-05-17 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_tasks_tsk_acc_date_remove_tasks_tsk_cmp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 17), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateTimeField(blank=True, default='2023-05-17 14:13', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='req_acc_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата принятия'),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='req_cmp_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reg_date',
            field=models.DateTimeField(blank=True, default='2023-05-17 14:13', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tsk_dedl_date',
            field=models.DateTimeField(blank=True, default='2023-05-17 14:13', null=True, verbose_name='Дата дедлайна'),
        ),
    ]
