# Generated by Django 4.0 on 2023-05-19 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_computers_arrival_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='computers',
            name='arrival_date',
            field=models.DateField(blank=True, default=datetime.date(2023, 5, 19), verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repairrequests',
            name='reg_date',
            field=models.DateTimeField(blank=True, default='2023-05-19 15:48', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reg_date',
            field=models.DateTimeField(blank=True, default='2023-05-19 15:48', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tsk_dedl_date',
            field=models.DateTimeField(blank=True, default='2023-05-19 15:48', null=True, verbose_name='Дата дедлайна'),
        ),
    ]
